kind: Service
apiVersion: v1
metadata:
  name: serice-pod
spec: 
  selector: # labels are used as selectors
    Project: expense 
    Component: backend
    environment: dev
  ports:
  - protocol: TCP
    port: 80
    targetport: 80
---
kind: Pod
apiVersion: v1
metadata:
  name: backend
  labels:
    Project: expense
    Component: backend
    environment: dev
spec:
  containers: 
  - name: nginx
    image: nginx
  


